name: release

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    branches:
      - main
    inputs:
      force-release:
        default: false
        description: "try to release even with no changes"
        required: false
        type: boolean

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: release-it
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'node'
          cache: 'yarn'
      - name: install
        run: yarn --frozen-lockfile
      - name: generate
        run: yarn generate
      - name: test
        run: yarn test
      - id: changes
        name: detect changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(update): automated client update"
      - name: release
        if: github.event.inputs.force-release == 'true' || steps.changes.outputs.changes_detected == 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
