name: test

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: install
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
        env:
          TRANSITLAND_API_KEY: ${{ secrets.TRANSITLAND_API_KEY }}
          TRANSITLAND_URL: ${{ secrets.TRANSITLAND_URL }}
