name: test

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: install
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
        env:
          TRANSITLAND_API_KEY: ${{ secrets.TRANSITLAND_API_KEY }}
          TRANSITLAND_URL: ${{ secrets.TRANSITLAND_URL }}
