name: test

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: install
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
        env:
          TRANSITLAND_API_KEY: ${{ secrets.TRANSITLAND_API_KEY }}
          TRANSITLAND_URL: ${{ secrets.TRANSITLAND_URL }}
